### ISSUE TITLE
Doesn't seem to work with Vue 3.0.0-rc.10

### ISSUE THREAD

**Issue by HackyDev** [boussadjra/vue-spring-calendar#5]
Hey! I've just created a template project with `vue ui` and installed your calendar through `npm`. 

Here are some warnings I get when I run `npm run serve`:
```
warning  in ./node_modules/@vue/composition-api/dist/vue-composition-api.module                               .js

"export 'default' (imported as 'Vue') was not found in 'vue'

 warning  in ./node_modules/@vue/composition-api/dist/vue-composition-api.module                               .js

"export 'default' (imported as 'Vue') was not found in 'vue'
```

Here's an error in the browser:

![1](https://user-images.githubusercontent.com/70698428/92482367-5dc46180-f209-11ea-8526-76c04ad2229a.png)

Btw, thank you for this project and all the help you do on stackoverflow.

**Comment by boussadjra** [comment]
@HackyDev thank you for raising this issue, this component is created using Vue 2 and it doesn't support vue 3 yet, i will try to release new version when the vue 3 will be officially released with stable version.
