### ISSUE TITLE
next step month error

### ISSUE THREAD

**Issue by tranthanhtung04101995** [boussadjra/vue-spring-calendar#8]
Failed to execute 'insertBefore' on 'Node': The node before which the new node is to be inserted is not a child of this node.

**Comment by boussadjra** [comment]
Thanks for raising this issue, please provide the steps to reproduce this issue

**Comment by tranthanhtung04101995** [comment]
When accessing the website: https://boussadjra.github.io/vue-spring-calendar/, choose the month, go back 1 month with the error

**Comment by boussadjra** [comment]
Yes you're right, thanks, I will try to fix it when I have enough time

**Comment by tranthanhtung04101995** [comment]
Hope you will solve this problem soon?

**Comment by boussadjra** [comment]
@tranthanhtung04101995  I will try to fix it this weekend

**Comment by boussadjra** [comment]
I fixed that issue and thanks again for raising this issue
